### ISSUE TITLE
Importing `.icls` file doesn't work

### ISSUE THREAD

**Issue by carusog** [Fasteel/jetbrains-github-color-schemes#2]
Hi, I downloaded the `.zip` folder, and, following installation instruction in `READ.ME`, I tried to import it from `File > Import Settings… > Github (by Fasteel).icls` but it doesn't work.
I see other colour schemes are exported as `.jar` and that format works perfectly.
Btw, I would avoid parentheses in file name.

**Comment by Fasteel** [comment]
Now, I exported both .icls and .jar
